### PR TITLE
27 Trying to Delete Dupe Folder Issue with Bartek Fix Moving to Testing!

### PR DESCRIPTION
**Pull request by BartekAlickii**
I deleted the duplicate folder and replaced all the necessary files! This means I moved the newer child folders into the parent directory!

### CODE REVIEW

**Comment by ianreyes1** [comment]
Sounds good bro

**Comment by ianreyes1** [comment]
I review it, it looks  good.

**Comment by ianreyes1** [comment]
That's on me

**Comment by BartekAlickii** [comment]
This issue was solved in the TA session. Unrelated to needing to delete this. Theory debunked....

**Pull request closed without merging**
